Repository iampavangandhi/TradeByte, pull requests merged in 2020-08, with the labels that each got.

#15 Added files 1
  README.md
  config/data-compact.json
  models/Transaction.js
  routes/api/addBalance.js
  routes/api/cart.js
  routes/api/edit.js
Labels: enhancement

#18 Fix/#10
  .DS_Store
  .gitignore
  README.md
  public/.DS_Store
  public/images/TradeByte -Favicon.png
  public/images/TradeByte.png
Labels: good first issue

#25 Fix 02
  app.js
  routes/api/view.js
  views/view.ejs
Labels: add feature, enhancement

#26 Fix/#9
  .gitignore
  app.js
  models/Stock.js
  models/User.js
  project-plan/.DS_Store
  project-plan/ui-designs/.DS_Store
  public/images/.DS_Store
  routes/api/cart.js
  routes/api/transaction.js
  views/cart.ejs
  views/transaction.ejs
Labels: add feature, bug, help wanted

#37 Building the View Page and managing it's backend and frontend both. #29 #36
  helpers/getOverview.js
  helpers/getPrice.js
  public/css/style.css
  routes/api/cart.js
  routes/api/market.js
  routes/api/view.js
  views/cart.ejs
  views/layouts/app.ejs
  views/market.ejs
  views/partials/_nav.ejs
  views/portfolio.ejs
  views/view.ejs
Labels: Issue, add feature, backend, frontend

#39 Improvement in Market Section UI and Fixing portfolio page bugs Fix/#28
  public/css/style.css
  routes/api/market.js
  views/market.ejs
  views/portfolio.ejs
Labels: bug, enhancement, frontend

#40 added symbol instead of image #28
  views/market.ejs
Labels: bug, enhancement, frontend

#45 Worked on Cart Frontend and Backend both while fixing some UI issues. Fix/#29
  helpers/getCompanyNameAndLogo.js
  routes/api/cart.js
  views/cart.ejs
  views/market.ejs
  views/partials/_nav.ejs
  views/portfolio.ejs
Labels: add feature, backend, bug, enhancement, frontend

#48 Fix cart/#29
  helpers/getCompanyNameAndLogo.js
  routes/api/transaction.js
  views/cart.ejs
Labels: backend, bug

#49 Added Tailwind manually and minified the css file. Fixes #47
  package-lock.json
  package.json
  postcss.config.js
  public/css/style.css
  style/tailwind.css
  tailwind.config.js
  views/layouts/app.ejs
Labels: add feature, frontend

#57 Fix/#44
  app.js
  public/javascript/script.js
  routes/api/market.js
  routes/api/portfolio.js
  routes/api/search.js
  routes/api/view.js
  views/portfolio.ejs
  views/search.ejs
Labels: add feature, backend, enhancement

#55 Send Email at the time of transaction with nodemailer OAuth2. Fixes #46 - Task 2 (Complete)
  app.js
  helpers/emailHelper.js
  helpers/helper.js
  package-lock.json
  package.json
  routes/api/addBalance.js
  routes/api/auth.js
  routes/api/cart.js
  routes/api/market.js
  routes/api/transaction.js
  routes/api/user.js
  views/portfolio.ejs
  views/transaction/transaction.ejs
Labels: add feature, backend, bug, enhancement, frontend

#62 Implemented Referral System, code formatted and fixed some typos
  app.js
  middleware/auth.js
  models/Transaction.js
  package-lock.json
  package.json
  public/css/style.css
  routes/api/addBalance.js
  routes/api/done.js
  routes/api/index.js
  routes/api/portfolio.js
  routes/api/transaction.js
  routes/api/user.js
  views/done.ejs
  views/transaction/history.ejs
Labels: add feature, backend, database, enhancement

#63 Fix/#59
  app.js
  public/css/tailwind.css
  routes/api/edit.js
  views/edit.ejs
  views/partials/_nav.ejs
Labels: backend, enhancement, frontend

#66 #65 add searchbox in market
  views/market.ejs
  views/portfolio.ejs
Labels: enhancement, frontend

#68 Fix/#60
  public/css/style.css
  public/css/tailwind.css
  public/images/desktop-mockup.png
  public/images/mobile-buy-mockup.png
  public/images/mobile-market-mockup.png
  public/images/mobile-payment-mockup.png
  public/images/mobile-view-mockup.png
  public/images/profile.jpg
  tailwind.config.js
  views/addBalance.ejs
  views/layouts/login.ejs
  views/login.ejs
  views/market.ejs
  views/partials/_nav.ejs
  views/signup.ejs
Labels: add feature, documentation, enhancement, frontend

#73 :) #67
  config/data-total.json
Labels: enhancement

#75 Ui improvements
  public/css/style.css
  public/css/tailwind.css
  tailwind.config.js
  views/addBalance.ejs
  views/edit.ejs
  views/layouts/app.ejs
  views/layouts/login.ejs
  views/login.ejs
  views/market.ejs
  views/partials/_footer.ejs
  views/partials/_nav.ejs
  views/partials/_search.ejs
  views/portfolio.ejs
  views/search.ejs
  views/signup.ejs
  views/transaction/history.ejs
  views/transaction/transaction.ejs
Labels: add feature, bug, enhancement, frontend
